language: ruby
cache: bundler
rvm: 2.2.1

sudo: false

before_install: 'bundle install'

addons:
  sauce_connect:
    username: $SAUCE_USERNAME
    access_key: $SAUCE_ACCESS_KEY

script: 'bundle exec rake travis'
